/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

/*
 * This file is autogenerated by kernel/tools/hardware_gen.py
 */

#pragma once

#include <types.h>
#include <psci.h>

#define MAX_NUM_REGIONS 1

struct elfloader_driver;

struct elfloader_device {
    const char *compat;
    volatile void *region_bases[MAX_NUM_REGIONS];
    struct elfloader_driver *drv;
};

struct elfloader_cpu {
    const char *compat;
    const char *enable_method;
    word_t cpu_id;
    word_t extra_data;
};

#ifdef DRIVER_COMMON
struct elfloader_device elfloader_devices[] = {
    {
        /* /timer */
        .compat = "arm,armv8-timer",
        .region_bases = {
            (void *)0,
        },
    },
    {
        /* /soc/uart@2800d000 */
        .compat = "arm,pl011",
        .region_bases = {
            (void *)0x2800d000,
        },
    },
    {
        /* /psci */
        .compat = "arm,psci-1.0",
        .region_bases = {
            (void *)0,
        },
    },
};

struct elfloader_cpu elfloader_cpus[] = {
    {
        /* /cpus/cpu@0 */
        .compat = "phytium,ftc310",
        .enable_method = "psci",
        .cpu_id = 0x200,
        .extra_data = PSCI_METHOD_SMC
    },
    {
        /* /cpus/cpu@1 */
        .compat = "phytium,ftc310",
        .enable_method = "psci",
        .cpu_id = 0x201,
        .extra_data = PSCI_METHOD_SMC
    },
    { .compat = NULL /* sentinel */ },
};
#else
extern struct elfloader_device elfloader_devices[];
extern struct elfloader_cpu elfloader_cpus[];
#endif